34 add noise animation
GameWithPixels/DiceFirmware pull request #41
Opened 2022-08-29 11:24 UTC by David-Chernis

- Added a built in noise animation to reduce overall memory usage of the animation due to the image. 
- Modified the nextRand function for the purpose of the animation
- Also added some method comments to Animation.h

2022-08-29 16:55 UTC, jeansimonet requested changes

2022-08-30 09:23 UTC, obasille commented on src/animations/animation_noise.cpp
> +			for(int i = 0; i < numFaces; i++){
This is the behavior David described at our meeting, every "step" he's lighting a random number of faces to add a bit of variability (currently random is between 1 and 2 faces, but that can be changed or made configurable of course)

2022-08-30 09:26 UTC, obasille commented on src/animations/animation_noise.cpp
> +				blinkDurations[faceIndex] = preset->duration * preset->blinkDuration / 255 + curRand % 20;
It's for randomly selecting which new face to light up.
It might be worth checking if the selected face is not already lit up though.

2022-08-30 09:31 UTC, obasille commented on src/animations/animation_noise.cpp
> +				blinkDurations[faceIndex] = preset->duration * preset->blinkDuration / 255 + curRand % 20;
Indeed @David-Chernis there is one `curRand = Utils::nextRand(curRand);` missing before it's being (re)used by `int faceIndex = curRand%20;`

Also for clarity I think it's best to have the curRand update just above where it's being used (=> move line 76 to above line 79)

2022-08-30 12:51 UTC, jeansimonet commented on src/animations/animation_noise.cpp
> +				blinkDurations[faceIndex] = preset->duration * preset->blinkDuration / 255 + curRand % 20;
I don't think that's true from reading the code...

2022-08-30 14:19 UTC, David-Chernis commented on src/animations/animation_noise.cpp
> +				blinkDurations[faceIndex] = preset->duration * preset->blinkDuration / 255 + curRand % 20;
yeah, that was to do with the problem I seemed to have with skipping for face indices

2022-08-30 14:22 UTC, David-Chernis commented on src/animations/animation_noise.cpp
> +				blinkDurations[faceIndex] = preset->duration * preset->blinkDuration / 255 + curRand % 20;
this specific curRand%20 was completely random, realized I should have made this a preset parameter for adding variability to blink durations

2022-08-30 14:23 UTC, David-Chernis commented on src/animations/animation_noise.cpp
> +			for(int i = 0; i < numFaces; i++){
The loop is used to create a delay between blinks and then the numFaces determines how many faces to light up at a time in one cycle. This cycle's length is determined by the blinkCount where we divide the length of the animation by the total number of blinks that we want.

2022-08-30 20:19 UTC, David-Chernis commented on src/animations/animation_noise.cpp
> +				blinkDurations[faceIndex] = preset->duration * preset->blinkDuration / 255 + curRand % 20;
So I changed the comments on that loop to hopefully also better explain it

2022-08-31 01:07 UTC, merged